@startuml UC1 SD Slave
skinparam style strictuml

mainframe **SD** UC1: Registreret rumskift (Slave)

actor Bruger as bruger
participant "<<boundary>>\nDør sensor" as dør
participant "<<boundary>>\nRum sensor" as rum
participant "<<boundary>>\nID sensor" as ID
participant "<<control>>\nUC1: Registreret rumskift (Slave)" as slave
participant "<<boundary>>\nX10" as X10


alt registrering i døren
bruger ->> dør : Går gennem dør
dør ->> slave : Detektering sendes
activate slave
else registrering i tomt rum
deactivate slave
bruger ->> rum : Bevægelse i tomt rum
rum ->> slave : Detektering sendes
activate slave
else registrere i forventet tomt rum
deactivate slave
bruger ->> ID : Registrering i ikke forventet rum
ID ->> slave : Detektering sendes
activate slave
end
slave -> slave : setNormalPowerUsage()
slave -> X10 : sendActivity(slaveNr, activity)
activate X10
slave <<-- X10 : Done
deactivate X10
slave -> slave : setLowPowerUsage()
deactivate slave
@enduml