@startuml UC1 SD Slave
skinparam style strictuml

mainframe **SD** UC1: Registreret rumskift (Slave)

actor Bruger as bruger
participant "<<boundary>>\nDør sensor" as dør
participant "<<boundary>>\nRum sensor" as rum
participant "<<boundary>>\nID sensor" as ID
participant "<<control>>\nUC1: Registreret rumskift (Slave)" as slave
participant "<<domain>>\nX10Communication" as X10
participant "<<boundary>>\nX10 Network" as X10Net

alt Registrering
bruger ->> dør : Går gennem dør
dør ->> slave : Detektering sendes
activate slave
else
deactivate slave
bruger ->> rum : Bevægelse i tomt rum
rum ->> slave : Detektering sendes
activate slave
else
deactivate slave
bruger ->> ID : Registrering i ikke forventet rum
ID ->> slave : Detektering sendes
activate slave
end
slave -> slave : setNormalPowerUsage()
slave -> X10 : sendActivity(slaveNr, activity)
slave <<-- X10 : Done
slave -> slave : setLowPowerUsage()
deactivate slave
@enduml