@startuml BDD IPRS
skinparam defaultTextAlignment center

mainframe **BDD** Intelligent pattern recognition system


object "<<Block>>\nIntelligent pattern recognition system" as IPRS {
**ports**
in userInput: force
in adminCommand: force
in afstand: fysisk
in bevægelse: fysisk
in IDinformation: chip
out userInformation: light
out adminInformation: light
out aktuatorCommand: digital
}

object "<<Block>>\nCentral styringsenhed" as master {
**ports**
in slaveInformation: X10
out slaveCommand: X10
in boardCommand: UART
out boardInformation: UART
out masterLog: UART
}

object Informationspanel <<Block>> {
**ports**
in boardInformation: UART
out boardCommand: UART
in userInput: force
out userInformation: light
}

object Computer <<Block>> {
**ports**
in masterLog: UART
out adminInformation: light
in adminCommand: force
}
' Måske mus/tastetur

object "<<Block>>\nSensor slave" as Sensor_slave {
**ports**
in slaveCommand: X10
out slaveInformation: X10
in sensorInformation: analog
in sensorInformation: digital
in sensorInformation: UART
}

object "<<Block>>\nAktuator slave" as Aktuator_slave {
**ports**
in slaveCommand: X10
out aktuatorCommand: digital
}

object "<<Block>>\nDør sensor" as Dør_sensor {
**ports**
in afstand: fysisk
out sensorInformation: analog
}

object "<<Block>>\nRum sensor" as Rum_sensor {
**ports**
in bevægelse: fysisk
out sensorInformation: digital
}

object "<<Block>>\nID sensor" as ID_sensor {
**ports**
in IDinformation: chip
out sensorInformation: UART
}


IPRS *-- master
IPRS *-- Informationspanel
IPRS *-- Computer
IPRS *-- "0..254" Aktuator_slave
IPRS *-- "0..255" Sensor_slave
Sensor_slave  *-- "0..1" Dør_sensor 
Sensor_slave *-- "0..1" Rum_sensor
Sensor_slave *-- "0..1" ID_sensor
@enduml