@startuml
' Default param deffinition
skinparam style strictuml
skinparam DefaultFontSize 16
skinparam DefaultFontName times new roman
skinparam ArrowFontSize 16
skinparam ArrowThickness 2.2
skinparam Linetype poly
skinparam ranksep 100
skinparam nodesep 200
hide empty members

' Class definition
Class "**Bruger**" as BR{
- navn
- id
- position
}

Class "**Lyd**" as LD{
- status
    
}

Class "**Lys**" as LS{
- status
}

Class "**Varme**" as V{
- status 
}


Class "**Aktuator Slave**" as AS{
- status
}


Class "**Sensor Slave**" as SS{
- status
}

Class "**Dør Sensor**" as DS{
- detektering
}

Class "**Rum Sensor**" as RS{
- detektering
}

Class "**Id Sensor**" as IS{
- detektering
}

Class  "**Master**" as ME{
- rumindhold
- rumstatus
- midlertidiglog
}

Class "**Computer**" as COM{
- log
}

Class "**Informationspanel**" as INFO {
- rumindhold
}

Class "**administrator**" as admin {
- navn
- id
- username
- password
}

' Conection definition
@enduml