@startuml DM IPRS
' Default param deffinition
skinparam style strictuml
skinparam DefaultFontSize 16
skinparam DefaultFontName times new roman
skinparam ArrowFontSize 16
skinparam ArrowThickness 2.2
skinparam Linetype poly
skinparam ranksep 100
skinparam nodesep 100
hide empty members


mainframe **DM** IPRS

' Class definition
Class "**Bruger**" as BR{
- navn
- id
- position
}

Class "**Lyd**" as LD{
- status
    
}

Class "**Lys**" as LS{
- status
}

Class "**Varme**" as V{
- status 
}


Class "**Aktuator Slave**" as AS{
- status
}


Class "**Sensor Slave**" as SS{
- status
- log
}

Class "**Dør Sensor**" as DS{
- detektering
}

Class "**Rum Sensor**" as RS{
- detektering
}

Class "**Id Sensor**" as IS{
- detektering
}

Class  "**Master**" as ME{
- rumindhold
- rumstatus
- midlertidiglog
}

Class "**Computer**" as COM{
- log
}

Class "**Informationspanel**" as INFO {
- rumindhold
}

Class "**administrator**" as ADMIN {
- navn
- id
- username
- password
}

' Conection definition
BR -- INFO : > Checker rumindhold

BR -- IS : > Aktivere
BR -- DS : > Aktivere
BR -- RS : > Aktivere

RS "1" -- "1" SS : > Detektering
DS "1" -- "1" SS : > Detektering
IS "1" -- "1" SS : > Detektering

SS "1..*" -- "1" ME : > Aktivitet log
SS "1..*" -- "1" ME : < Statuts check

ME "1" -- "1" COM : > Log data
ME "1" -- "1" COM : < system ændring
ME "1" -- "1" INFO : > rumstatus
ME "1" -- "1" INFO : < Rumstatus efterspørgelse

ADMIN -- COM  : > adminstrer system

ME "1" -- "1..*" AS : > Sætter status
ME "1" -- "1..*" AS : < Status

AS "1" -- "1" LS : > sætter status
AS "1" -- "1" LD : > sætter status
AS "1" -- "1" V : > sætter status
@enduml