@startuml UC4 SD Master
skinparam style strictuml

mainframe **SD** UC4: Administrator login (Master)

participant "<<boundary>>\nUART Connection" as UARTCon
participant "<<domain>>\nUARTCommunication" as UART
participant "<<controller>>\nUC4: Administrator login (Master)" as master

activate master
UARTCon ->> master : Request log
UART <<- master : sendLog(log)
UARTCon <<-- UART : log
master -> master : deleteLog()
loop Så længe der ikke er logget ud
alt Print data
else Rediger system
UARTCon ->> master : newSystem
master -> master : changeSystem(newSystem)
UART <<- master : systemChanged()
UARTCon <<-- UART : System changed
else Initialisering
UARTCon ->> master : Request initialization of IPRS
master -> master : initialize() (UC 5)
UART <<- master : sendValidation(Validation)
UARTCon <<-- UART : Validation
else Log out
end
end
@enduml