@startuml UC4 class
' Default param deffinition
skinparam style strictuml
skinparam DefaultFontSize 16
skinparam ArrowFontSize 16
skinparam ArrowThickness 2.2
skinparam Linetype poly
skinparam ranksep 100
skinparam nodesep 100
skinparam classAttributeIconSize 0 
hide empty members


mainframe **Class** UC4: Administrator login

' Class definition

Class "**<<boundary>>**\n**PC interface**" as UI{
- password
- input
}

Class "**<<boundary>>**\n**UART Connection**" as UC{
- log
- System Calibrated
- Validation 
}


Class "**<<domain>>**\n**UARTCommunication**" as master{
- logRequest
- addSlave
- roomConnection
- calibrateRequest
- initialiseSystem
}

Class "**<<controller>>**\n**UC4: Administrator login**" as PC{
+ validate(password)
+ updateLog(log)
+ sendData(data)
+ printLog(log)
+ printData()
+ printRawData()
+ printSystemInfo()
+ showChangeOptions()
+ addSlave()
+ selectRoomConnection()
+ calibrateSystem()
+ selectSaveOnline()
+ initialiseSystem()
+ changeLog()
+ changePassword()
+ logOut()
+ exit()
- Log
- data
- addSlave
- roomConnection
- calibrateRequest
- initialiseSystem
- logRequest
- saveOption
- password
}

' Conection definition
PC <--> UI
PC <--> master
master <--> UC

@enduml