@startuml UC4 SD Master
skinparam style strictuml

mainframe **SD** UC4: Administrator login (Master)

participant "UART Connection" as UARTCon
participant "<<boundary>>\nUARTPC" as UARTPC
participant "<<boundary>>\nInterrupts" as in
participant "<<controller>>\nUC4: Administrator login (Master)" as master
participant "<<domain>>\nLog" as log

activate master
activate in
UARTCon ->> in : Request log
in <- master : stringReady()
in -->> master : true
UARTPC <<- master : SendString(log)
activate UARTPC
UARTCon <<- UARTPC : log
deactivate UARTPC
loop Så længe der ikke er logget ud
alt Print data
else Rediger system
UARTCon ->> in : newSystem
in <- master : stringReady()
in -->> master : true
master ->> log : log(rooms, users)
else Initialisering
UARTCon ->> in : Request initialization of IPRS
in <- master : stringReady()
in -->> master : true
master -> master : initialize() (UC 5)
UARTPC <<- master : SendString(Callibrated)
UARTCon <<-- UARTPC : Callibrated
else Log out
end
end
@enduml