@startuml UC4 STM

mainframe **STM** UC4: Administrator login - Print Data Menu

hide empty description

state "Print Data Menu" as data
state "Print Formated Log" as formated
state "Print Raw Data" as raw
state "Print System Info" as info

[*] --> data : Vælger Print Data
note on link
    Kommer fra "Muligheder" i hovedmenu
end note


data -> formated : Vælger formateret log
formated --> data : Returner

data --> raw : Vælger raw data
raw --> data : Returner

data --> info : Vælger system info
info --> data : Returner

data -> [*] : Går tilbage til hovedmenu

data : entry/updatePCLog(log)

formated : entry/printLog(log)

raw : entry/printRawData()

info : entry/printSystemInfo()

@enduml