
@startuml UC4 SMD

mainframe **SMD** UC4: Administrator login - Rediger System Menu

hide empty description

state "Rediger System Menu" as rediger
state "Add Slave" as addSlave
state "Select Room Connection" as selectRoom
state "Calibrate system" as cal
state "Select Save Options" as showOptions


note "Choice repræsenterer de forskellige muligheder i menuen \n 1. For Tilføj Slave \n 2. For Vælg Rumforbindelser \n 3. For Kalibrer System \n 4. For Vælg Gemme Indstilinger" as n1

[*] ---> rediger : Vælger Rediger System

note on link
    Staten "Rediger System"
    Kommer fra "Muligheder" i hovedmenu
end note

n1 --> rediger : Choice

rediger --> addSlave : Choice 1
addSlave --> rediger : Returner

rediger --> selectRoom : Choice 2
selectRoom --> rediger : Returner


rediger --> cal : Choice 3
cal --> rediger : Returner

rediger --> showOptions : Choice 4
showOptions --> rediger : Returner

rediger -> [*] : Går tilbage til hovedmenu

rediger : entry/showChangeOptions

addSlave : entry/addSlave()

selectRoom : entry/selectRoomConnections()

cal : entry/calibrateSystem()

showOptions : entry/selectSaveOnline()


@enduml