@startuml CD
skinparam style strictuml
skinparam classAttributeIconSize 0
hide empty members
skinparam classAttributeIconSize 0 

mainframe **CD** UC2

class "<<Controller>>\nAdministrer lys" as AL {
    - logLightStatus_ : uint8_t
    - outPin_ : int
    + updateLog() : void
}

class "<<boundary>>\nLys" as L {
    - on_ : bool
    + setStatus(LightStatus)
}

class "<<domain>>\nMaster" as M{
    <&minus> log : Log
}

M "1" --> "1..254" AL
AL  -->  L


@enduml