@startuml STM UC2

mainframe **STM** UC2

hide empty description

[*] --> IDLE : initieret

state IDLE : entry/setLowPowerUsage()
state IDLE : exit/setNormalPowerUsage()  

state SLUKKET : entry/lightOn()
state TÆNDT  : entry/lightOff()


IDLE --> TÆNDT : updateLog() / tændt
TÆNDT --> IDLE : Lys Tændt

IDLE --> SLUKKET : updateLog() / slukket
SLUKKET --> IDLE : Lys Slukket




@enduml