@startuml UC5 class
' Default param deffinition
skinparam style strictuml
skinparam DefaultFontSize 16
skinparam ArrowFontSize 16
skinparam ArrowThickness 2.2
skinparam Linetype poly
skinparam ranksep 100
skinparam nodesep 100
hide empty members
skinparam classAttributeIconSize 0

mainframe **Class** UC5: Initialisering

' Class definition

Class "**<<boundary>>**\n**Computer**" as PC{
}

Class "**<<boundary>>**\n**Sensor**" as sensor{
}


Class "**<<domain>>**\n**Slave**" as slave{
+ slaveInitialise()
+ sensorInitialise()
}

Class "**<<domain>>**\n**Informationspanel**" as panel{
+ panelInitialise()
}

Class "**<<controller>>**\n**UC5: Initialisering**" as master{
+ masterInitialise()
}

' Conection definition
master <--> PC
master <--> slave
master <--> panel
slave <-- sensor


@enduml