@startuml UC1 class Master
' Default param deffinition
skinparam style strictuml
skinparam DefaultFontSize 16
skinparam DefaultFontName times new roman
skinparam ArrowFontSize 16
skinparam ArrowThickness 2.2
skinparam Linetype poly
skinparam ranksep 100
skinparam nodesep 100
hide empty members


mainframe **Class** UC1: Registrer rumskifte (Master)

' Class definition
Class "**<<boundary>>**\n**Informationspanel**" as IP{
+ updateRoomstate(log)
- rooms
}

Class "**<<controller>>**\n**UC1: Registrer rumskifte (Master)**" as RR{
+ updateLog(activity)
- log
- activity
}

Class "**<<domain>>**\n**X10Communication**" as X10{
+ sendAck()
}

' Conection definition
RR --> X10
RR --> IP
@enduml